CREATE DATABASE inlock_games_dbFirst_manha
USE inlock_games_dbFirst_manha

CREATE TABLE Estudio
(
	IdEstudio UNIQUEIDENTIFIER PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
)

CREATE TABLE Jogo
(
	IdJogo UNIQUEIDENTIFIER PRIMARY KEY,
	IdEstudio UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Estudio(IdEstudio) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	DataLancamento DATE NOT NULL,
	Valor SMALLMONEY NOT NULL
)

CREATE TABLE TiposUsuario
(
	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	Titulo VARCHAR(100) NOT NULL
)

CREATE TABLE Usuario
(
	IdUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TiposUsuario(IdTipoUsuario) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR(100) NOT NULL
)


INSERT INTO Estudio 
VALUES(NEWID(),'SENAI'),(NEWID(),'SESI'),(NEWID(),'SEBRAE')

SELECT * FROM Estudio

INSERT INTO Jogo
VALUES (NEWID(),'5A5B9FE0-9326-476E-A872-79A33F3FE9C5','Ping-Pong','Jogo legal','2023-01-01',500),
	   (NEWID(),'5A5B9FE0-9326-476E-A872-79A33F3FE9C5','Jucamom','Caça Pokemon','2023-03-23',2.99)

SELECT * FROM Jogo

INSERT INTO TiposUsuario
VALUES (NEWID(), 'Administrador'),(NEWID(),'Comum')

SELECT * FROM TiposUsuario

INSERT INTO Usuario
VALUES(NEWID(),'4484A349-8837-4C4B-8158-36D8113B3F8E','admin@admin.com','admin'),
	  (NEWID(),'E0D1E00B-AEEB-4AB2-A30F-FA1055829A20','comum@comum.com','comum')

SELECT * FROM Usuario